# false = Белый список (только указанные IP)
# true = Блокировать всех (никто не может подключиться)
block-all: false

# Белый список IP-адресов
allowed-ips:
  - "127.0.0.1"
  - "localhost"
  # - "*"             # Пример: разрешить ВСЕМ (опасно!)

debug: false

check-interval: 20
